project:
  type: website

website:
  title: "Meilin Zheng"
  navbar:
    right:
      - icon: github
        href: https://github.com/MeZheng05
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/meilin-zheng-2865a2241/
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: data_analysis.qmd
        text: Data Analysis
   

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

